server {
    listen 443 ssl;
    http2 on;
    server_name opora.zheleznogame.ru;
    ssl_certificate /etc/letsencrypt/live/opora.zheleznogame.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/opora.zheleznogame.ru/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    return 301 https://opora.truthqwark.ru$request_uri;
}
